org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.java.home=d:/idea/install/IntelliJ IDEA 2026.1.4/jbr
org.gradle.java.installations.paths=d:/idea/install/IntelliJ IDEA 2026.1.4/jbr
systemProp.gradle.wrapper.distribution.network.timeout=60000
